version: "3.8"

services:
  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:497.0.0-emulators
    restart: unless-stopped
    ports:
      - "8085:8085"
    networks:
      - service-network
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=pubsubchub

networks:
  service-network:
    driver: bridge