GetConfig:
  group_id: 1
  GetConfigRequest:
    type_id: 1
    type: sync
    schema: "../data/config.yml#GetConfigRequest"
    topics:
      - GetConfig
    metadata:
      key: value
  GetConfigResponse:
    type_id: 2
    type: sync
    schema: "../data/config.yml#GetConfigResponse"
    topics:
      - GetConfig
    metadata:
      key: value